version: '3'

services:
    rabbit:
        image: rabbitmq:management
        environment:
            - RABBITMQ_DEFAULT_USER=quest
            - RABBITMQ_DEFAULT_PASS=quest
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - GET_HOSTS_FROM=dns
        labels:
            kompose.service.type: LoadBalancer

    worker_write_to_google:
        image: gcr.io/trends-217607/trends:e68c0d02e178f891dffe5b8a925757e9edbdbcb5
#        build: .
        command: celery -A trends worker -l info -Q write_to_google
        volumes:
            - ~/.ipython:/root/.ipython
        environment:
            - TOKEN_SHUTTERSTOCK=${_TOKEN_SHUTTERSTOCK}
        depends_on:
            - rabbit

    worker_research_task:
        image: gcr.io/trends-217607/trends:e68c0d02e178f891dffe5b8a925757e9edbdbcb5
#        build: .
        command: celery -A trends worker -P eventlet -c 10 -l info -Q research_task
        volumes:
            - ~/.ipython:/root/.ipython
        environment:
            - TOKEN_SHUTTERSTOCK=${_TOKEN_SHUTTERSTOCK}
        depends_on:
            - rabbit

    worker_combinations:
        image: gcr.io/trends-217607/trends:e68c0d02e178f891dffe5b8a925757e9edbdbcb5
#        build: .
        command: celery -A trends worker -P eventlet -c 10 -l info -Q combinations
        volumes:
            - ~/.ipython:/root/.ipython
        environment:
            - TOKEN_SHUTTERSTOCK=${_TOKEN_SHUTTERSTOCK}
        depends_on:
            - rabbit

    worker_shutterstock_search:
        image: gcr.io/trends-217607/trends:e68c0d02e178f891dffe5b8a925757e9edbdbcb5
#        build: .
        command: celery -A trends worker -l info -Q shutterstock_search
        volumes:
            - ~/.ipython:/root/.ipython
        environment:
            - TOKEN_SHUTTERSTOCK=${_TOKEN_SHUTTERSTOCK}
        depends_on:
            - rabbit

    web:
        image: gcr.io/trends-217607/trends:e68c0d02e178f891dffe5b8a925757e9edbdbcb5
#        build: .
        volumes:
            - ~/.ipython:/root/.ipython
        command: celery -A trends flower --port=80
        ports:
            - "80:80"
        depends_on:
            - worker_combinations
            - worker_shutterstock_search
            - worker_research_task
            - worker_write_to_google
        environment:
            - GET_HOSTS_FROM=dns
            - TOKEN_SHUTTERSTOCK=${_TOKEN_SHUTTERSTOCK}
        labels:
            kompose.service.type: LoadBalancer

    firefox:
        image: selenium/standalone-firefox-debug:3.14.0-iron
        container_name: firefox
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
            - "5901:5900"

    redis:
        image: redis:latest
        container_name: redis
        ports:
          - "6379:6379"
        volumes:
          - redis_db:/data

volumes:
  redis_db:
